apiVersion: apps/v1
kind: Deployment
metadata:
 name: cartservice
spec:
 selector:
   matchLabels:
     app: cartservice
 template:
   metadata:
     labels:
       app: cartservice
   spec:
     containers:
     - name: cartservice
       image: nangm/cartservice
       env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"

---
apiVersion: v1
kind: Service
metadata:
 name: cartservice
spec:
 type: NodePort
 selector:
   app: cartservice
 ports:
 - port: 80
   targetPort: 5000
   nodePort: 31322
